// <auto-generated />
using System;
using Infrastructure.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ConsumerContext))]
    [Migration("20240224105006_LatestChanges1")]
    partial class LatestChanges1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.ClsAddresses", b =>
                {
                    b.Property<Guid>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("pincode")
                        .HasColumnType("int");

                    b.HasKey("AddressID");

                    b.ToTable("T_Addresses");

                    b.HasData(
                        new
                        {
                            AddressID = new Guid("30e66da6-9598-4e02-8caf-2f163a427e2b"),
                            Address = "a",
                            City = "a_city",
                            CreatedBy = "",
                            CreatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2205),
                            UpdatedBy = "",
                            UpdatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2206),
                            pincode = 0
                        },
                        new
                        {
                            AddressID = new Guid("e30d8264-235c-4e0c-bfeb-cb87e3fd7050"),
                            Address = "b",
                            City = "b_city",
                            CreatedBy = "",
                            CreatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2208),
                            UpdatedBy = "",
                            UpdatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2208),
                            pincode = 0
                        },
                        new
                        {
                            AddressID = new Guid("5fd4aad9-4a90-4b1e-9a3d-e0a025fbeae0"),
                            Address = "c",
                            City = "c_city",
                            CreatedBy = "",
                            CreatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2216),
                            UpdatedBy = "",
                            UpdatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2217),
                            pincode = 0
                        },
                        new
                        {
                            AddressID = new Guid("2c9fcbb0-139e-4417-b08c-7c300484c86d"),
                            Address = "d",
                            City = "d_city",
                            CreatedBy = "",
                            CreatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2218),
                            UpdatedBy = "",
                            UpdatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2219),
                            pincode = 0
                        });
                });

            modelBuilder.Entity("Domain.ClsCompany", b =>
                {
                    b.Property<int>("companyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("companyId"), 1L, 1);

                    b.Property<int>("AddressID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TIN")
                        .HasColumnType("bigint");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("companyId");

                    b.ToTable("T_Company");

                    b.HasData(
                        new
                        {
                            companyId = 1,
                            AddressID = 1,
                            CreatedBy = "",
                            CreatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2053),
                            Email = "globalConnect@gmail.com",
                            Name = "Global Connect",
                            TIN = 10001L,
                            UpdatedBy = "",
                            UpdatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2055)
                        },
                        new
                        {
                            companyId = 2,
                            AddressID = 2,
                            CreatedBy = "",
                            CreatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2056),
                            Email = "swiftImports@gmail.com",
                            Name = "Swift Imports",
                            TIN = 10002L,
                            UpdatedBy = "",
                            UpdatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2057)
                        },
                        new
                        {
                            companyId = 3,
                            AddressID = 3,
                            CreatedBy = "",
                            CreatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2090),
                            Email = "exportExperts@gmail.com",
                            Name = "Export Experts",
                            TIN = 10003L,
                            UpdatedBy = "",
                            UpdatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2091)
                        },
                        new
                        {
                            companyId = 4,
                            AddressID = 4,
                            CreatedBy = "",
                            CreatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2092),
                            Email = "tradeNavigation@gmail.com",
                            Name = "Trade Navigation",
                            TIN = 10004L,
                            UpdatedBy = "",
                            UpdatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2092)
                        });
                });

            modelBuilder.Entity("Domain.ClsDeclaration", b =>
                {
                    b.Property<Guid>("DeclarationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeclarationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExportCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImportCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("consigneeTin")
                        .HasColumnType("bigint");

                    b.Property<long>("consignerTin")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("expectedDateOfDelivery")
                        .HasColumnType("datetime2");

                    b.Property<long>("payerTin")
                        .HasColumnType("bigint");

                    b.Property<decimal>("totalCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("transportationMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeclarationId");

                    b.ToTable("T_Declaration");
                });

            modelBuilder.Entity("Domain.ClsEvent", b =>
                {
                    b.Property<int>("eventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("eventId"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("events")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("eventId");

                    b.ToTable("T_Event");
                });

            modelBuilder.Entity("Domain.ClsGoodsItem", b =>
                {
                    b.Property<int>("GoodsItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoodsItemId"), 1L, 1);

                    b.Property<string>("CommodityCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeclarationID")
                        .HasColumnType("int");

                    b.Property<decimal>("DutyCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("GoodsItemId");

                    b.ToTable("T_GoodsItem");
                });

            modelBuilder.Entity("Domain.ClsMaterialCommodityMapping", b =>
                {
                    b.Property<long>("CommodityCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CommodityCode"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DutyPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("CommodityCode");

                    b.ToTable("T_MaterialCommodityMapping");

                    b.HasData(
                        new
                        {
                            CommodityCode = 8517L,
                            CreatedBy = "",
                            CreatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2240),
                            DutyPercentage = 0.4m,
                            MaterialType = "Electronic",
                            Price = 1000m,
                            UpdatedBy = "",
                            UpdatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2241)
                        },
                        new
                        {
                            CommodityCode = 6101L,
                            CreatedBy = "",
                            CreatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2242),
                            DutyPercentage = 0.3m,
                            MaterialType = "Clothing",
                            Price = 2000m,
                            UpdatedBy = "",
                            UpdatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2243)
                        },
                        new
                        {
                            CommodityCode = 7206L,
                            CreatedBy = "",
                            CreatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2244),
                            DutyPercentage = 0.2m,
                            MaterialType = "Steel",
                            Price = 3000m,
                            UpdatedBy = "",
                            UpdatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2244)
                        },
                        new
                        {
                            CommodityCode = 3901L,
                            CreatedBy = "",
                            CreatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2245),
                            DutyPercentage = 0.1m,
                            MaterialType = "Plastic",
                            Price = 4000m,
                            UpdatedBy = "",
                            UpdatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2245)
                        },
                        new
                        {
                            CommodityCode = 2709L,
                            CreatedBy = "",
                            CreatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2247),
                            DutyPercentage = 0.5m,
                            MaterialType = "CrudeOil",
                            Price = 5000m,
                            UpdatedBy = "",
                            UpdatedOn = new DateTime(2024, 2, 24, 10, 50, 5, 981, DateTimeKind.Utc).AddTicks(2247)
                        });
                });

            modelBuilder.Entity("Domain.ClsMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("delcaration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("T_Message");
                });
#pragma warning restore 612, 618
        }
    }
}
